#! /bin/sh
set -euo pipefail

MACHINEID=${MACHINEID:-/etc/machine-id}
DBUS_MACHINEID=${DBUS_MACHINEID:-/var/lib/dbus/machine-id}

## Write Systemd log
# $1 = info 
#      warning
#      emegr
sysdlog() {
	echo $2 | systemd-cat -t altlinux-newinstance -p $1
}

sysdlog info "System setup for new instance"
/sbin/systemd-firstboot --delete-root-password --setup-machine-id --force
echo "" > ${DBUS_MACHINEID}
dbus-uuidgen --ensure
rm -rf /etc/udev/rules.d/70-persistent-net.rules
find /etc/net/ifaces -mindepth 1 -maxdepth 1 -type d -not -name lo -not -name default -not -name unknown -exec rm -fr {} \;
rm -rf /etc/openssh/ssh_host_*
#rm -rf /var/log/*
sysdlog info "System setup for new instance complete"
